### ISSUE TITLE
Làm việc với git

### ISSUE THREAD

**Issue by mirikado** [duck-tech/LabOne#3]
Tạo branch develop from brach master
Ex: gco -b develop
Tạo branch sprint_1 from branch develop
Ex: gco -b sprint_1

**Comment by duck-tech** [comment]
anh em đã tạo 2 branch và không biết là có thể xem branch ở dưới dạng tree được không anh

**Comment by mirikado** [comment]
checkout về develop rồi tạo lại sprint_1
xong xoá nhánh flutter_1 đi
rồi assign lại cho a

**Comment by mirikado** [comment]
Xong!
