### ISSUE TITLE
Write your first Flutter app, Hello world!

### ISSUE THREAD

**Issue by mirikado** [duck-tech/LabOne#4]
https://flutter.dev/docs/get-started/codelab
Step 1: Create the starter Flutter app
Hello world!
Step 2: Use an external package
Step 3: Add a Stateful widget
Step 4: Create an infinite scrolling ListView
Note: Sẽ làm sau khi tạo xong nhánh sprint_1

**Comment by duck-tech** [comment]
![image](https://user-images.githubusercontent.com/53960004/79678690-3b18b880-8228-11ea-8fb2-ee8916c1b77b.png)

xong rồi anh!

**Comment by mirikado** [comment]
LGTM!
